### ISSUE TITLE
Significant lag on large resultset

### ISSUE THREAD

**Issue by mfrauenhoffer** [jenius-apps/nightingale-rest-api-client#6] opened 2019-04-08 02:29 UTC
There is significant lag when trying to select and copy a text response that is large. The size of the result back is 362.279 KB; when trying to select a value from the response, Nightingale locks up and is not usable for a good several minutes. Currently consuming 400 MB of RAM and constantly using ~18% CPU on a Core i7 quad core machine with 32 GB of RAM.

**Comment by dpaulino** [comment] 2019-04-08 06:20
Thanks for reporting this. Out of curiosity, any chance I could get a sample text response that you were expecting back? Or perhaps I could get the endpoint you were using? If not, no worries. I can simulate it based on the size you described. Again, thanks for reporting. Going to investigate this further and report back my findings here.

**Comment by mfrauenhoffer** [comment] 2019-04-08 22:18
Unfortunately, I can't give you the response as it contains company information. I'm more than willing to share any additional information to help you reproduce and debug. Thank you! I love the tool so far!

**Comment by dpaulino** [comment] 2019-04-10 02:44
Spent a bit of time reproducing this, and it is indeed the similar to the issue that others have reported a few weeks back. Unfortunately no easy fix for this, since it seems that there are currently no UWP text controls capable of handling large text. Here's an issue related to trying to build a scalable text control: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2858 

Going to spend some more time on this soon.

**Comment by dpaulino** [comment] 2019-04-25 17:23
There's a uservoice request for the platform team to build a UWP control that can handle large strings: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37090696-virtualized-richeditbox

Please help upvote it if you can @mfrauenhoffer

**Comment by dpaulino** [comment] 2019-05-14 04:30
We have added a fix for the crash. Essentially, we are checking the size of the response. If it passes 500kb, then we are blocking the rendering of the text. We will provide an option to download the response instead. 

While this is not an elegant solution, it should suffice until Nightingale switches to a UI control that can handle large text.

This bug fix will be available in the next update.

**Comment by mfrauenhoffer** [comment] 2019-05-14 14:11
Thanks Daniel! I will try it out in the new build. I have also upvoted the UserVoice request as well!

**Comment by dpaulino** [comment] 2019-05-14 15:11
No problem. The new build has been deployed to our private preview group. If all goes well, it should be publicly available in a couple days

**Comment by dpaulino** [comment] 2019-05-17 06:42
The new build (v2.0.8) is now publicly available.

**Closed by dpaulino** 2019-05-17 06:42 UTC
Labels: bug
