### ISSUE TITLE
Abnormal exit

### ISSUE THREAD

**Issue by kekeflp** [jenius-apps/nightingale-rest-api-client#31] opened 2019-12-19 11:58 UTC
When I call the environment variable and send it, an error is reported。
![Snipaste_2019-12-19_19-54-55](https://user-images.githubusercontent.com/19684835/71171798-a3b35100-2299-11ea-84b7-6231fa55d487.png)
![Snipaste_2019-12-19_19-55-56](https://user-images.githubusercontent.com/19684835/71171800-a3b35100-2299-11ea-8aed-2ac2791eb44e.png)

**Comment by dpaulino** [comment] 2019-12-19 15:52
Thanks for reporting this. I'll look into it asap.

**Comment by Kirlac** [comment] 2020-01-16 05:38
From my breif debugging attempts here, it seems the issue only occurs when using an environment variable in the host part of the url.

Eg. using the test API call: `https://jsonplaceholder.typicode.com/posts?userId=1`

What works:
- Sending a GET request to this hardcoded url works as expected
- Variables seem to work as expected in query params (both for key and value) so sending the same request as `https://jsonplaceholder.typicode.com/posts?userId={{userId}}` where `{{userId}} = 1` works as expected, as does using `https://jsonplaceholder.typicode.com/posts` in the url and putting `userId = {{userId}}` in the queries list
- Sending the same request as `https://jsonplaceholder.typicode.com/{{route}}` with `{{route}} = posts` and the above query params works as expected

What doesn't work:
- Variables in the base part of the url (using the above query params)
  - `{{scheme}}://jsonplaceholder.typicode.com/posts` with `{{scheme}} = https`
  - `https://{{host}}/posts` with `{{host}} = jsonplaceholder.typicode.com` 
  - Or any part thereof eg. `https://{{subdomain}}.typicode.com/posts` or `https://jsonplaceholder.{{domain}}/posts`

**Comment by dpaulino** [comment] 2020-01-16 05:39
@Kirlac big thank you for the detailed repro steps! Looking into this deeper now!

**Comment by Kirlac** [comment] 2020-01-16 06:14
Thanks for looking into this @dpaulino. No problem, I'm happy to help - hopefully I gave you something useful there. I can see this being my go-to rest debugger (replacing postman once I upgrade to premium for more collections/environments/etc), but I was in the process of doing a "trial run" when I ran into this bug. Hopefully it's not a big one to fix - I can see this potentially causing problems with chaining variables later on but haven't got far enough in my testing to see how that works yet

**Comment by dpaulino** [comment] 2020-01-17 05:21
@Kirlac I tried to reproduce it in v3.2.4, and I think the issue may have been addressed in one of the bug fixes I did. 
![image](https://user-images.githubusercontent.com/7649589/72586064-3cdb8480-38a5-11ea-8fff-7ccd02da1414.png)

Any chance you're in the preview program to test this out? You can join [here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAANAAQduPxpURU8zSUFNUTBYRDVSUkhJS0JQOE8yTFZYTy4u) if you're interested. 

I'll do a bit more testing, but if I can't repro this in 3.2.4, then I think it may have been fixed.

**Comment by dpaulino** [comment] 2020-01-17 21:30
@kekeflp @Kirlac Nightingale v3.2.4 was just released to the public. Please give it a try and let me know if the bug you're seeing still persists. From my own testing, I could not reproduce the bug in v3.2.4. Please let me know as soon as possible. Thanks!

**Comment by Kirlac** [comment] 2020-01-19 23:18
Hi @dpaulino sorry for the late response. I have just had the chance to test this with the v3.2.4 release and I can confirm the issue appears to be resolved for me. Thanks!

**Comment by dpaulino** [comment] 2020-01-19 23:41
Great, thanks for confirming!

**Closed** 2020-01-19 23:42 UTC
Labels: bug
