### ISSUE TITLE
[Bug] Some fields of Form Data aren't responding correctly.

### ISSUE THREAD

**Issue by lucimarckjsdias** [jenius-apps/nightingale-rest-api-client#14] opened 2019-10-10 15:31 UTC
I made the same request on two clients: Nightingale and Insomnia. Compare the responses.

![image](https://user-images.githubusercontent.com/30981574/66582732-3f189f00-eb50-11e9-9095-6f4436b24bcc.png)

Some fields on Nightingale look like weren't sent. It's a bug or I missing something? I tried to complete the content type fields too, but it didn't work.

**Comment by dpaulino** [comment] 2019-10-12 04:21
Thanks for the screen shot. Investigating now.

**Comment by dpaulino** [comment] 2019-10-12 04:47
I've identified the cause of the bug, and I have applied a fix. Thank you SO much for reporting this. I will be preparing to deploy this to the preview program as soon as possible. Stay tuned for updates.

**Comment by dpaulino** [comment] 2019-10-12 06:35
The fix has been submitted to the store for the preview program. I will report back once it's available to preview members.

**Comment by dpaulino** [comment] 2019-10-12 22:02
V3.0.22 has been deployed to preview members. Are you in the preview program? Can you confirm if it works?

**Comment by lucimarckjsdias** [comment] 2019-10-13 01:22
Is working now! Thanks ❤

![image](https://user-images.githubusercontent.com/30981574/66709622-59ac6d00-ed36-11e9-8a26-1105e4350e1e.png)

**Closed** 2019-10-13 01:23 UTC
Labels: bug
