### ISSUE TITLE
How to simulate a form file upload ?

### ISSUE THREAD

**Issue by TonyHenrique** [jenius-apps/nightingale-rest-api-client#60] opened 2020-05-07 01:06 UTC
What do I have to inform on these fields to simulate a form file upload ?

![image](https://user-images.githubusercontent.com/6307623/81243271-c397a700-8fe5-11ea-8961-2bced830686e.png)

This is how I did the same using Postman

![image](https://user-images.githubusercontent.com/6307623/81243292-ceead280-8fe5-11ea-9791-c70cb16d49cf.png)

**Comment by dpaulino** [comment] 2020-05-12 04:14
@TonyHenrique I think you've answered this before but what happens if you add a key to that form data item? do you get the same error?

**Comment by dpaulino** [comment] 2020-05-12 05:32
I've been unable to reproduce that exact error message. However, I spent some time diving into .NET's http libraries. It seems that when adding form data items, a key is required for each item. Nightingale doesn't seem to handle form data items without keys gracefully. I *think* that's what causes your error. 

As a fix, I'm going to make it clear in Nightingale's UI that keys are required for form data items, and I will make the app better handle situations when keys are empty

**Comment by TonyHenrique** [comment] 2020-05-12 22:18
Having these parameters:
![image](https://user-images.githubusercontent.com/6307623/81751193-55d7f900-9485-11ea-8076-804388b8e003.png)

I get this Exception

**Comment by dpaulino** [comment] 2020-05-15 15:48
The changes are now available in v3.6.10. Closing ticket, but please feel free to reopen it if you feel it's still not solving your issue!

> Maybe the solution is Nightingale put some default values on the required fields, as it seems that Postman does.

I was thinking this as well. Perhaps I'll make "default" the default key string?

**Closed by dpaulino** 2020-05-15 15:48 UTC
Labels: bug
